Update batch calculations
jepusto/SingleCaseES pull request #44
Opened 2021-06-02 04:26 UTC by manchen07

I added aggregate and weighting arguments and replaced `do()` with `summarise()`. Aggregating is done for long format and then converted to wide format if required. Need to discuss this more. Also need to discuss how to aggregate confidence intervals.

2021-06-02 15:30 UTC, jepusto commented on R/calculate-effect-sizes.R
> +    dplyr::summarise(calc_ES(condition = .data[[condition]],
Well that simplifies things!

2021-06-02 15:33 UTC, jepusto commented on R/calculate-effect-sizes.R
> +    if (weighting == "1/V") {
Handle weights by first computing the weighting variable (depending on the `weighting` argument), then summarizing using weighted averages.

2021-06-02 15:34 UTC, jepusto commented on R/calculate-effect-sizes.R
> +      res <-
This is fine for handling CI calculations with aggregated effect sizes.

2021-06-03 15:13 UTC, manchen07 commented on R/calculate-effect-sizes.R
> +    Est <- SE <- n <- CI_lower <- CI_upper <- NULL
This is used for handling the "no visible binding for global variable" in R CMD check (https://www.r-bloggers.com/2019/08/no-visible-binding-for-global-variable/).

2021-06-09 21:09 UTC, manchen07 commented on R/calculate-effect-sizes.R
> +if(getRversion() >= "2.15.1")  utils::globalVariables(c("ES", "Est", "SE", "CI_upper", "CI_lower"))
This is used to handle the warning message "no visible binding for global variable" in R CMD check.

2021-07-23 02:44 UTC, jepusto requested changes
I made a few small tweaks on this branch. Three issues for your consideration:

### Syntax for `aggregate` 

Right now `aggregate`  will have to be a subset of the variables in `grouping` in order to work. The syntax is also the opposite of what I had in mind. I think it will be more intuitive if we 

1. Calculate ES estimates grouping by _both_ `grouping` and `aggregate`
2. Summarize the ES estimates and SEs _over_ the levels of `aggregate`, while grouping by `grouping`  (and `ES`).

So for example, in the `Schmidt2007` data, if we want one ES for each `Behavior_type` and `Case_pseudonym`, with effects calculated for each `Phase_num` and the averaged together, the syntax would be
```
  ES_agg_CI <- 
    batch_calc_ES(dat = Schmidt2007,
                  grouping = c(Behavior_type, Case_pseudonym),
                  aggregate = Phase_num,
                  weighting = "1/V",
                  condition = Condition,
                  outcome = Outcome,
                  ES = c("LRRi","LRRd", "Tau"),
                  improvement = direction,
                  scale = "count",
                  bias_correct = TRUE,
                  confidence = .95,
                  format = "long")
```

I've modified the unit tests to use the desired syntax. Please update the code to pass the tests.

### `Weighting` specification

Right now, the error handling for the `weighting` argument says that it "must be a variable name or a string specifying '1/V' or 'equal'." But I think it should have to be one of the allowed strings. Right now, if you specify a variable name I think it will default to equal weighting, which doesn't seem right. I've added a unit test to this effect.

### Example with `aggregate`

Please add an example to the documentation demonstrating use of the `aggregate` argument.

2021-08-03 20:25 UTC, jepusto approved these changes

2021-08-03 20:36 UTC, merged