test SCD_effect_sizes shiny app
jepusto/SingleCaseES pull request #56
Opened 2021-10-01 22:12 UTC by manchen07

- Added unit tests for single-entry and batch-entry calculator.
- Added snapshot-based shinytest for batch calculator.

2021-10-04 15:12 UTC, jepusto requested changes
Overall this approach is spot-on. Really nice work figuring out how to do this!!! I have a few suggestions and follow-ups:
- In `test-SCD-effect-sizes.R`, would it make sense to configure the app just one time, rather than doing it separately for each of the tests? It seems like doing so might speed things up.
- For testing the single ES calculator, combine `check_single_NOMs()` and `check_single_param()` into one function with argument `ES_family`.
- For testing the batch calculator, can you abstract your approach into a function so that we can test all three of the included examples?
- For testing the batch calculator, I think we should also include tests that involve uploading a csv and uploading an xlsx file, so that we can ensure that those pieces of the app are working correctly.
- Add `skip_on_cran()` because we don't need to have CRAN running these checks.

2021-10-04 16:55 UTC, jepusto commented
See here for guidance on resolving the PhantomJS error causing most of the R-CMD-checks to fail:
https://stackoverflow.com/questions/64491156/github-actions-r-package-r-cmd-check-phantomjs-not-found

2021-10-08 19:23 UTC, manchen07 commented on tests/testthat/test-SCD-effect-sizes.R
> +  output_xlsx <- check_load("McKissick.xlsx")
I used McKissick data for checking both excel and csv file uploading. Thought this makes the code simpler compared to using two different data sets for excel and csv uploading checking.

2021-10-09 01:54 UTC, jepusto approved these changes

2021-10-09 01:55 UTC, merged