Debug PoGO calculation
jepusto/SingleCaseES pull request #92
Opened 2023-03-03 20:39 UTC by manchen07

Hi James,

I've added the three datasets that Megan used (based on the authors and year). Could you double check whether I got the right articles? Or we could ask them for references.

I've added unit tests for these three datasets, comparing Megan's results and the package results. I think the discrepancies on Casey 1978 is caused by her way of rounding. However, for the added tests in the `test-SCD-effect-sizes.R` for PoGO, it seems that there is some discrepancy between app results and package results, and I'm not sure why...I won't have time for debugging the rest of the day, so I just send the pull request anyway. I could work more on this tomorrow if needed.

Man

2023-03-03 21:41 UTC, jepusto requested changes
1. Please rename the following files so that they do not have spaces and revise any code the calls these files:
* tests/testdata/CSES FINAL dataset.csv
* tests/testdata/CSES FINAL dataset.xlsx

2023-03-03 21:42 UTC, jepusto commented on auxiliary/prepare_POGO.R
> +  ungroup()
Please revise so that Byiers2014 is saved as a data.frame rather than a tibble.

2023-03-03 22:49 UTC, jepusto commented
It looks like there are two issues with the unit tests for PoGO in the web app. One was that the "by-hand" calculation of the ES did not include the argument for `aggregate = phase_pair_calculated`. I added that in the commit that I just pushed. The other issue is that there were numerical differences between the .csv file and the .xlsx file. I re-saved the csv file with a larger number of digits so that the files agree. It should work now.

2023-03-04 19:27 UTC, manchen07 commented
I've updated the data and relevant tests. Everything looks good except one error with the windows-latest CMD check. It's related to the dropdown menu of improvement direction. I'm not sure if it is a big deal since other CMD checks have passed.

2023-03-04 19:56 UTC, jepusto approved these changes

2023-03-04 20:07 UTC, merged